stages:
  - build
  - deploy

cache:
  key: "$CI_PROJECT_NAMESPACE"
  paths:
    - node_modules

build_dev:
  only:
    - /^v\d+\.\d+\.\d+-dev$/
  stage: build
  image: node:16.12.0
#  artifacts:
#    name: "${CI_COMMIT_TAG}"
#    paths:
#      - dist/
#    expire_in: 7 days
  script:
    - yarn config set registry https://registry.npmmirror.com
    - yarn
    - yarn build
  allow_failure: false

deploy_dev:
  only:
    - /^v\d+\.\d+\.\d+-dev$/
  stage: deploy
  image: ansible/centos7-ansible
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir ~/.ssh/
    - echo -e "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - echo -e "${ANSIBLE_HOSTS}" > ~/hosts
    - echo -e "${ANSIBLE_PLAYBOOK}" > ~/playbook.yml
    - cd ./dist && tar zcf /tmp/dist.tar.gz *
    - ansible-playbook ~/playbook.yml -i ~/hosts --extra-vars "{'server_name':'dev_server'}"
  allow_failure: false
